"""empty message

Revision ID: 6fba30b98f99
Revises: 610bcd63bd93
Create Date: 2023-12-10 11:28:39.082561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fba30b98f99'
down_revision = '610bcd63bd93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_make', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('car_model', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('car_year', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('car_year')
        batch_op.drop_column('car_model')
        batch_op.drop_column('car_make')

    # ### end Alembic commands ###
